<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <!-- The .csproj file uses ../../Directory.Build.props as a source for some configurations -->
    <PropertyGroup>
        <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
        <AssemblyName>itext.publications.signing_examples.aws_kms_test</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="NUnit" Version="3.12.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\itext.publications.signing-examples.aws-kms\itext.publications.signing-examples.aws-kms.csproj" />
    </ItemGroup>
</Project>