<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <!-- The .csproj file uses ../../Directory.Build.props as a source for some configurations -->
    <PropertyGroup>
        <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
        <AssemblyName>itext.publications.signing_examples.cng_utimaco_test</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="nunit" Version="3.13.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
        <PackageReference Include="System.Security.Cryptography.Cng" Version="6.0.0-preview.4.21253.7" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\itext.publications.signing-examples.simple\itext.publications.signing-examples.simple.csproj" />

        <PackageReference Include="itext" Version="9.8.0-SNAPSHOT" />
    </ItemGroup>
</Project>