<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <!-- The .csproj file uses ../../Directory.Build.props as a source for some configurations -->
    <PropertyGroup>
        <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
        <AssemblyName>itext.publications.signing_examples.simple</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Security.Cryptography.Pkcs" Version="6.0.5" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="itext" Version="9.8.0-SNAPSHOT" />
        <PackageReference Include="itext.bouncy-castle-adapter" Version="9.8.0-SNAPSHOT" />
    </ItemGroup>
</Project>